### ISSUE TITLE
Microphone key

### ISSUE THREAD

**Issue by aymanbagabas** [zer0nka/linux-on-huawei-matebook-d-14-amd#1]
Hey, could you please try [this](https://github.com/aymanbagabas/Huawei-WMI) driver to fix the microphone key? I've been working on it for a while and I need testers. I would really appreciate the help. Thank you

**Comment by zer0nka** [comment]
Sorry mate, i don't have matebook. Just looking for running well linux on amd ryzen.

**Comment by aymanbagabas** [comment]
> Sorry mate, i don't have matebook. Just looking for running well linux on amd ryzen.

You don't have the matebook D 14 AMD?

**Comment by zer0nka** [comment]
yes, only Acer Nitro 5 AN515-42-R8DY

**Comment by aymanbagabas** [comment]
Ok, thank you!
