### ISSUE TITLE
Restart touchpad script doesn't work

### ISSUE THREAD

**Issue by alex27riva** [zer0nka/linux-on-huawei-matebook-d-14-amd#3]
Hi, I recently installed Linux Mint 20.1 on my Matebook D 14 (2018), but there remains that bug that prevents the touchpad from working after waking from sleep.
I tried your script but doen't work. (I replaced the name of the device and the name of the user).
From `dmesg` the error is `i2c_hid i2c-ELAN2203:00: i2c_hid_get_input: IRQ triggered but there's no data`
Is the a way to fix this annoying problem?
Thanks

**Comment by zer0nka** [comment]
sorry for late response, 
original author of this repo is https://gitlab.com/cscs
his repo https://gitlab.com/cscs/linux-on-huawei-matebook-d-14-amd/
I don't have any Matebook D
